"""Defines Pydantic models for structured data exchange within the MAS.

This module contains all the core Pydantic schemas that ensure type-safe and
validated data transfer between different components of the multi-agent
system, such as between controllers and workers, and for defining the agent's
actions on the graph.
"""

from enum import Enum
from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class MessageType(str, Enum):
    """Enumeration for the type of message between agents."""

    INSTRUCTION = "INSTRUCTION"
    REPORT = "REPORT"


class WorkerInstruction(BaseModel):
    """Schema for an instruction sent from a Controller to a Worker."""

    message_type: MessageType = MessageType.INSTRUCTION
    intent: str = Field(...)

    def to_json(self) -> str:
        """Serialize the model to a JSON string."""
        return self.model_dump_json(exclude_none=True)


class WorkerReportStatus(str, Enum):
    """Enumeration for the status of a Worker's report."""

    FOUND = "FOUND"
    NOT_FOUND = "NOT_FOUND"
    ERROR = "ERROR"


class WorkerReport(BaseModel):
    """Schema for a report sent from a Worker back to a Controller."""

    message_type: MessageType = MessageType.REPORT
    status: WorkerReportStatus = Field(...)
    content: str = Field(...)
    max_score: float = Field(default=0.0)

    def to_json(self) -> str:
        """Serialize the model to a JSON string."""
        return self.model_dump_json(exclude_none=True)


class AgentActionType(str, Enum):
    """Enumeration of the possible logical actions an agent can perform on the graph."""

    CITE_FACT = "cite_fact"
    CITE_LAW = "cite_law"
    SUPPORT_CLAIM = "support_claim"
    REBUT_CLAIM = "rebut_claim"


class AgentAction(BaseModel):
    """Schema for a single, atomic action to be performed on the debate graph.

    This is the fundamental unit of an agent's turn. A list of these actions
    is generated by the Controller at the end of its decision-making process.
    """

    action_type: AgentActionType = Field(...)
    content: str = Field(...)
    target_id: Optional[str] = Field(None)
    source_id: Optional[str] = Field(None)
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)

    def to_json(self) -> str:
        """Serialize the model to a formatted JSON string."""
        return self.model_dump_json(exclude_none=True, indent=2)


class ResourceRequirement(BaseModel):
    """Schema for the output of a Controller's needs assessment actions.

    This model structures the Controller's decision on whether to delegate a
    task (like fact-checking) to a worker.
    """

    need: bool = Field(...)
    reasoning: str = Field(...)
    intent: Optional[str] = Field(None)

    def to_json(self) -> str:
        """Serialize the model to a formatted JSON string."""
        return self.model_dump_json(exclude_none=True, indent=2)


AGENT_ACTION_SCHEMA_DESC = """
    【AgentAction 函数参数规范】

    你必须在函数参数 `actions` 中提供一个数组 `[...]`，其中每个对象代表一个图谱操作。

    **核心字段**:
    - `action_type` (string): 你的意图。必须是 "cite_fact", "cite_law", "support_claim", "rebut_claim" 之一。
    - `content` (string): 你的观点内容。
    - `source_id` (string | null): 动作的“来源”或“依据”。
    - `target_id` (string | null): 动作的“目标”。
    - `metadata.reason_brief` (string): 动作的简要推理链，格式建议为
      `争点:...;依据:...;动作理由:...`。必须简洁，不要展开冗长思维过程。

    **辩论策略约束**:
    - 动作组合应同时覆盖 `SUPPORT` 与 `CONFLICT`，避免单边输出。
    - 围绕我方关键主张构建可采纳子集，并补齐必要防御。
    - 目标是提升我方在首选扩展竞争中的可采纳优势。

    **【重要】规则按 `action_type` 定义**:

    1.  **当 `action_type` 是 "cite_fact" 或 "cite_law" (引用证据/法条)**:
        -   `source_id`: **必须**是图谱中一个已存在的 `FACT` 或 `LAW` 节点的ID。
        -   `target_id`:
            -   如果你想用这个证据支持一个**已存在的观点**，这里就填那个观点的ID。
            -   如果你想用这个证据提出一个**新观点**，这里必须是 `null`。
        -   `content`: 描述你基于该证据提出的观点。

    2.  **当 `action_type` 是 `"support_claim"` 或 `"rebut_claim"` (支持/反驳观点)**:
        -   `target_id`: **必须**是图谱中一个已存在的 `CLAIM` 节点的ID (即被你支持或反驳的目标)。
        -   `source_id`:
            -   如果你想用一个**已存在的观点**去支持/反驳目标，这里就填那个观点的ID。
            -   如果你想提出一个**新观点**去支持/反驳目标，这里必须是 `null`。
        -   `content`: 描述你的新观点。

    **示例（即 `actions` 字段的值）**:
    ```json
    [
        {
            "action_type": "cite_fact",
            "content": "基于借条事实，我认为被告有还款义务。",
            "source_id": "FACT_9e8c2d", 
            "target_id": null,
            "metadata": {
                "reason_brief": "争点:还款义务;依据:借条与履行记录;动作理由:以事实支撑我方主张。"
            }
        },
        {
            "action_type": "cite_law",
            "content": "依据民法典支持我方关于利息的观点。",
            "source_id": "LAW_34da21",
            "target_id": "CLAIM_ff562a",
            "metadata": {
                "reason_brief": "争点:利息支持范围;依据:法条构成要件;动作理由:补齐法律适用链条。"
            }
        },
        {
            "action_type": "rebut_claim",
            "content": "对方的观点忽略了合同中的附加条款，因此不成立。",
            "source_id": null, 
            "target_id": "CLAIM_4eda56",
            "metadata": {
                "reason_brief": "争点:条款解释;依据:合同附加条款;动作理由:直接削弱对方关键主张。"
            }
        }
    ]
    ```
"""
