export { CompatAdapterFacade, createCompatAdapter } from "./adapter";
export type { AdapterOptions } from "./client";

export type {
  AdapterCapabilities,
  DebateConvergence,
  CreateSessionInput,
  DebateMetrics,
  DebatePhase,
  DebateSnapshot,
  DebateTermination,
  EngineAdapter,
  GraphAdapter,
  GraphDiffView,
  GraphEdge,
  GraphNode,
  GraphView,
  InsightAdapter,
  MemoryView,
  MemoryInsightItem,
  TaskLayerGraph,
  TaskLayerNode,
  TaskLayerEdge,
  FrontendSnapshotListItem,
  FrontendSnapshotLoadResult,
  SessionAdapter,
  SnapshotIndexItem,
  TeamFlowMessage,
  TeamFlowMessagePhase,
  TeamFlowMessageRole,
  TeamFlowTurn,
  TimelineEvent,
  TurnArtifact,
} from "./types";
