export { CompatAdapterFacade, createCompatAdapter } from "./adapter";
export type { AdapterOptions } from "./client";

export type {
  AdapterCapabilities,
  DebateConvergence,
  CreateSessionInput,
  DemoKeyframe,
  DemoRunResult,
  DebateMetrics,
  DebatePhase,
  DebateSnapshot,
  DebateTermination,
  DebugBundleView,
  EngineAdapter,
  GraphAdapter,
  GraphDiffView,
  GraphEdge,
  GraphNode,
  GraphView,
  InsightAdapter,
  MemoryView,
  MemoryInsightItem,
  MemoryCaseSnapshot,
  TaskLayerGraph,
  TaskLayerNode,
  TaskLayerEdge,
  ReplayExportView,
  SessionAdapter,
  SnapshotIndexItem,
  TimelineEvent,
  TurnArtifact,
} from "./types";
